name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

env:
  platforms: "linux/arm/v7,linux/arm64/v8,linux/amd64"
  registry: "ghcr.io/benediktbertsch/sharelatex"

jobs:
  build:
    defaults:
      run:
        working-directory: "./backend"
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-build-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up QEMU to build multiplatform docker images
      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
      with:
        version: latest
    - name: Login into registry
      uses: docker/login-action@v1.12.0
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Calculate metadata
      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
      id: meta
      with:
        images: ghcr.io/benediktbertsch/cf-ddns
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
      env:
        DOCKER_METADATA_ANNOTATIONS_LEVELS: index
    - name: Build and deploy docker images
      working-directory: ./server-ce
      run: make && docker image ls
        